# Generated by Django 5.1.6 on 2025-02-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=7, verbose_name='Placa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('saida', models.DateTimeField(auto_now=True)),
                ('veiculos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimentacoes', to='base.veiculo', verbose_name='Veículo')),
            ],
        ),
    ]
